version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"  # Make sure this is mapping the correct port
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app/server.py  # Ensure this starts the Flask app automatically
